sudo: false

services:
  - docker

language: c

compiler:
  - gcc

before_install:
  - docker pull bohrium/ubuntu:16.04
  - docker build -t bohrium_release -f package/docker/bohrium.dockerfile .

env:
  global:
      - BH_GPU_VERBOSE=true

  matrix:

      # UNI stack
      - BH_STACK=uni BH_UNI_PROF=true RUN="python /bohrium/test/python/run.py --file /bohrium/test/python/tests/test_primitives.py --cont-on-error"


notifications:
  slack: bohrium:BCAEW8qYK5fmkt8f5mW95GUe

script:
    - docker run -t -e BH_STACK -e BH_CPU_JIT_LEVEL -e BH_BCEXP_GPU_REDUCE1D -e BH_GPU_VERBOSE -e RUN bohrium_release
