sudo: false

services:
  - docker

language: c

compiler:
  - gcc

before_install:
  - docker pull bohrium/ubuntu:16.04
  - docker build -t bohrium_release -f package/docker/bohrium.dockerfile .

env:
  matrix:

      # OPENMP stack
      #     - BH_STACK=openmp BH_OPENMP_PROF=true RUN="python /bohrium/test/python/run.py /bohrium/test/python/tests/test_*.py && python /bohrium/test/python/numpytest.py --file test_benchmarks.py"

        #     - BH_STACK=openmp BH_OPENMP_SERIAL_FUSION=true BH_OPENMP_PROF=true RUN="python /bohrium/test/python/run.py /bohrium/test/python/tests/test_*.py && python /bohrium/test/python/numpytest.py --file test_benchmarks.py"

      # OPENCL stack
      #      - BH_STACK=opencl BH_OPENMP_PROF=true RUN="python /bohrium/test/python/run.py /bohrium/test/python/tests/test_*.py && python /bohrium/test/python/numpytest.py --file test_benchmarks.py"

      - BH_STACK=openmp BH_OPENMP_PROF=true RUN="python3 /bohrium/test/python/run.py /bohrium/test/python/tests/test_*.py && python3 /bohrium/test/python/numpytest.py --file test_benchmarks.py"

notifications:
  slack: bohrium:BCAEW8qYK5fmkt8f5mW95GUe

script:
    - docker run -t -e BH_STACK -e BH_CPU_JIT_LEVEL -e BH_BCEXP_GPU_REDUCE1D -e BH_GPU_VERBOSE -e RUN bohrium_release
