services:
  - docker

language: c

compiler:
  - gcc

before_install:
  - docker pull bohrium/ubuntu:16.04
  - docker build -t bohrium_release -f package/docker/bohrium.dockerfile .

env:
  global:
    - BH_OPENMP_PROF=true
    - BH_OPENMP_VOLATILE=true
    - BH_OPENCL_PROF=true
    - BH_OPENCL_VOLATILE=true

  matrix:
    # Python 2.7
    - BH_STACK=openmp PYTHON_EXEC=python2.7
    - BH_STACK=opencl PYTHON_EXEC=python2.7

    # Python 3.5
    - BH_STACK=openmp PYTHON_EXEC=python3.5
    - BH_STACK=opencl PYTHON_EXEC=python3.5

notifications:
  slack: bohrium:BCAEW8qYK5fmkt8f5mW95GUe

script:
  - docker run -t -e BH_STACK -e BH_OPENMP_PROF -e BH_OPENCL_PROF -e PYTHON_EXEC -e BH_OPENMP_VOLATILE -e BH_OPENCL_VOLATILE bohrium_release
