language: c
compiler:
  - gcc
  - clang
env:
   - OMP_NUM_THREADS=1 BH_CPU_BIND=0 BH_STACK="stack_gpu" BH_GPU_VERBOSE=true LD_LIBRARY_PATH="$HOME/.local/lib:$LD_LIBRARY_PATH"
   - OMP_NUM_THREADS=1 BH_CPU_BIND=0 BH_STACK="stack_gpu" BH_GPU_VERBOSE=true BH_GPU_COMPILE=sync LD_LIBRARY_PATH="$HOME/.local/lib:$LD_LIBRARY_PATH"
   - OMP_NUM_THREADS=4 BH_CPU_JIT_LEVEL=3 BH_BCEXP_SIGN=1 LD_LIBRARY_PATH="$HOME/.local/lib:$LD_LIBRARY_PATH"
   - OMP_NUM_THREADS=4 BH_CPU_JIT_LEVEL=3 BH_BCEXP_SIGN=0 LD_LIBRARY_PATH="$HOME/.local/lib:$LD_LIBRARY_PATH"
   - OMP_NUM_THREADS=4 BH_CPU_JIT_LEVEL=1 BH_BCEXP_SIGN=1 LD_LIBRARY_PATH="$HOME/.local/lib:$LD_LIBRARY_PATH"
   - OMP_NUM_THREADS=4 BH_CPU_JIT_LEVEL=1 BH_BCEXP_SIGN=0 LD_LIBRARY_PATH="$HOME/.local/lib:$LD_LIBRARY_PATH"
   - BH_STACK="stack_cpu_greedy" OMP_NUM_THREADS=4 BH_CPU_JIT_LEVEL=3 BH_BCEXP_SIGN=1 LD_LIBRARY_PATH="$HOME/.local/lib:$LD_LIBRARY_PATH"
   - BH_STACK="stack_cpu_greedy" OMP_NUM_THREADS=4 BH_CPU_JIT_LEVEL=3 BH_BCEXP_SIGN=0 LD_LIBRARY_PATH="$HOME/.local/lib:$LD_LIBRARY_PATH"
   - BH_STACK="stack_cpu_greedy" OMP_NUM_THREADS=4 BH_CPU_JIT_LEVEL=1 BH_BCEXP_SIGN=1 LD_LIBRARY_PATH="$HOME/.local/lib:$LD_LIBRARY_PATH"
   - BH_STACK="stack_cpu_greedy" OMP_NUM_THREADS=4 BH_CPU_JIT_LEVEL=1 BH_BCEXP_SIGN=0 LD_LIBRARY_PATH="$HOME/.local/lib:$LD_LIBRARY_PATH"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get build-dep -qq python-numpy
  - sudo apt-get install -qq python python-numpy python-cheetah cython swig cmake libboost-all-dev libboost-dev libboost-filesystem-dev libboost-system-dev libboost-serialization-dev libboost-thread-dev libhwloc-dev freeglut3 freeglut3-dev libxmu-dev libxi-dev fglrx fglrx-dev opencl-headers
script:
  - df -h
  - mkdir bdir && cd bdir && cmake -DCMAKE_BUILD_TYPE=Release .. && make -j4 && make install
  - BASEDIR=${HOME}/build/bh107 && git clone --depth=1 git://github.com/bh107/benchpress.git ${BASEDIR}/benchpress && cd ${BASEDIR}/benchpress && . util/setbpenv.bash && cd ${BASEDIR}
  - python bohrium/test/python/numpytest.py $BH_EXCLUDE
  - df -h
  - du -h ${HOME}/.local/var
