sudo: required

services:
  - docker

language: c

compiler:
  - gcc

before_install:
  - echo ${TRAVIS_COMMIT}
  - wget raw.githubusercontent.com/bh107/bohrium/${TRAVIS_COMMIT}/package/docker/ubuntu14.04/Dockerfile
  - ls
  - docker build -t bh107 .

script:
  - ls
