services:
  - docker

language: python

env:
  global:
    - BH_OPENMP_PROF=true
    - BH_OPENMP_VOLATILE=true
    - BH_OPENCL_PROF=true
    - BH_OPENCL_VOLATILE=true
    - TEST_RUN="/bh/test/python/run.py /bh/test/python/tests/test_*.py"
    - BENCHMARK_RUN="/bh/test/python/numpytest.py --file test_benchmarks.py"

script:
  - env | grep -E "BH_|EXEC" | sort > .env-file
  - cat .env-file
  - docker pull bohrium/wheel:latest
  - docker run -t --env-file .env-file bohrium/wheel

jobs:
  include:
    - stage: build docker image
      script:
        - docker login -u="$DOCKER_USER" -p="$DOCKER_PASSWORD"
        - docker build -t bohrium/wheel -f package/docker/create_wheel.dockerfile .
        - docker push bohrium/wheel

    - stage: verify
    # Test suite
      env: BH_STACK=openmp EXEC="python2.7 $TEST_RUN"
    - env: BH_STACK=opencl EXEC="python2.7 $TEST_RUN"
    - env: BH_STACK=openmp BH_OPENMP_MONOLITHIC=true EXEC="python2.7 $TEST_RUN"
#    - env: BH_STACK=proxy_opencl EXEC="bh_proxy_backend -a localhost -p 4200 & python2.7 /bohrium/test/python/run.py /bohrium/test/python/tests/test_!(nobh).py"
    - env: BH_STACK=openmp EXEC="python3.6 $TEST_RUN"
    - env: BH_STACK=opencl EXEC="python3.6 $TEST_RUN"

    # Benchmarks
    - env: BH_STACK=openmp EXEC="python2.7 $BENCHMARK_RUN"
    - env: BH_STACK=opencl EXEC="python2.7 $BENCHMARK_RUN"
    - env: BH_STACK=openmp EXEC="python3.6 $BENCHMARK_RUN"
    - env: BH_STACK=opencl EXEC="python3.6 $BENCHMARK_RUN"

notifications:
  slack: bohrium:BCAEW8qYK5fmkt8f5mW95GUe
