language: c
compiler:
  - gcc
  - clang
env:
   - BH_STACK="stack_gpu"
   - OMP_NUM_THREADS=4 BH_CPU_JIT_LEVEL=3 BH_BCEXP_SIGN=1 LD_LIBRARY_PATH="$HOME/.local/lib:$LD_LIBRARY_PATH"
#  - OMP_NUM_THREADS=4 BH_CPU_JIT_LEVEL=3 BH_BCEXP_SIGN=0 LD_LIBRARY_PATH="$HOME/.local/lib:$LD_LIBRARY_PATH"
#  - OMP_NUM_THREADS=4 BH_CPU_JIT_LEVEL=1 BH_BCEXP_SIGN=1 LD_LIBRARY_PATH="$HOME/.local/lib:$LD_LIBRARY_PATH"
#  - OMP_NUM_THREADS=4 BH_CPU_JIT_LEVEL=1 BH_BCEXP_SIGN=0 LD_LIBRARY_PATH="$HOME/.local/lib:$LD_LIBRARY_PATH"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get build-dep -qq python-numpy
  - sudo apt-get install -qq python python-numpy python-cheetah cython swig cmake libboost-all-dev libboost-dev libboost-filesystem-dev libboost-system-dev libboost-serialization-dev libboost-thread-dev libhwloc-dev freeglut3 freeglut3-dev libxmu-dev libxi-dev fglrx fglrx-dev opencl-headers
script:
  - mkdir bdir && cd bdir && cmake -DCMAKE_BUILD_TYPE=Release .. && make -j4 && make install
  - python ../test/python/numpytest.py --exclude=test_benchmarks.py
