language: generic

before_install:
  - ./.travis/before_install.sh

env:
  global:
    - BH_OPENMP_PROF=true
    - BH_OPENMP_VOLATILE=true
    - BH_OPENCL_PROF=true
    - BH_OPENCL_VOLATILE=true

matrix:
  include:
    # Linux - Python 2.7 - Docker
    - os: linux
      services: docker
      env: BH_STACK=openmp PYTHON_EXEC=python2.7
    - os: linux
      services: docker
      env: BH_STACK=opencl PYTHON_EXEC=python2.7

    # Linux - Python 3.5 - Docker
    - os: linux
      services: docker
      env: BH_STACK=openmp PYTHON_EXEC=python3.5
    - os: linux
      services: docker
      env: BH_STACK=opencl PYTHON_EXEC=python3.5

    # OS X - Python 2.7 - Metal
    - os: osx
      osx_image: xcode8.2
      env: BH_STACK=openmp PYTHON_EXEC=python2.7
      cache:
        directories:
          - $HOME/Library/Caches/Homebrew
    # - os: osx
    #   osx_image: xcode8.2
    #   env: BH_STACK=opencl PYTHON_EXEC=python2.7
    #   cache:
    #     directories:
    #       - $HOME/Library/Caches/Homebrew

install:
  - ./.travis/install.sh

script:
  - ./.travis/run.sh

notifications:
  slack: bohrium:BCAEW8qYK5fmkt8f5mW95GUe
