sudo: required

services:
  - docker

language: c

compiler:
  - gcc

before_install:
    - docker build -t bohrium -f package/docker/ubuntu14.04/bohrium.dockerfile .

env:
  matrix:
      - BH_STACK=stack_default
      - BH_STACK=stack_gpu

script:
    - docker run -t -e BH_STACK bohrium
