services:
  - docker

language: c

compiler:
  - gcc

before_install:
  - docker pull bohrium/ubuntu:16.04
  - docker build -t bohrium_release -f package/docker/bohrium.dockerfile .

env:
  global:
    - BH_OPENMP_PROF=true
    - BH_OPENMP_VOLATILE=true
    - BH_OPENCL_PROF=true
    - BH_OPENCL_VOLATILE=true

  matrix:
    # All test_*.py scripts
    - BH_STACK=openmp PY_EXEC=python2.7 TEST_EXEC="$PY_EXEC /bohrium/test/python/run.py /bohrium/test/python/tests/test_*.py"
    - BH_STACK=openmp BH_OPENMP_MONOLITHIC=true PY_EXEC=python2.7 TEST_EXEC="$PY_EXEC /bohrium/test/python/run.py /bohrium/test/python/tests/test_*.py"
    - BH_STACK=opencl PY_EXEC=python2.7 TEST_EXEC="$PY_EXEC /bohrium/test/python/run.py /bohrium/test/python/tests/test_*.py"
    - BH_STACK=openmp PY_EXEC=python3.5 TEST_EXEC="$PY_EXEC /bohrium/test/python/run.py /bohrium/test/python/tests/test_*.py"
    - BH_STACK=opencl PY_EXEC=python3.5 TEST_EXEC="$PY_EXEC /bohrium/test/python/run.py /bohrium/test/python/tests/test_*.py"

    # Test of the proxy backend
    - BH_STACK=proxy_opencl PY_EXEC=python2.7 TEST_EXEC="/usr/bin/bh_proxy_backend -a localhost -p 4200 & $PY_EXEC /bohrium/test/python/run.py /bohrium/test/python/tests/test_!(nobh).py"

    # The test_benchmarks.py script
    - BH_STACK=openmp PY_EXEC=python2.7 TEST_EXEC="$PY_EXEC /bohrium/test/python/numpytest.py --file test_benchmarks.py"
    - BH_STACK=opencl PY_EXEC=python2.7 TEST_EXEC="$PY_EXEC /bohrium/test/python/numpytest.py --file test_benchmarks.py"
    - BH_STACK=openmp PY_EXEC=python3.5 TEST_EXEC="$PY_EXEC /bohrium/test/python/numpytest.py --file test_benchmarks.py"
    - BH_STACK=opencl PY_EXEC=python3.5 TEST_EXEC="$PY_EXEC /bohrium/test/python/numpytest.py --file test_benchmarks.py"

notifications:
  slack: bohrium:BCAEW8qYK5fmkt8f5mW95GUe

script:
  - docker run -t -e BH_STACK -e BH_OPENMP_PROF -e BH_OPENCL_PROF -e BH_OPENMP_VOLATILE -e BH_OPENCL_VOLATILE -e BH_OPENMP_MONOLITHIC -e PY_EXEC -e TEST_EXEC bohrium_release
