sudo: false

services:
  - docker

language: c

compiler:
  - gcc

before_install:
  - docker pull bohrium/ubuntu:16.04
  - docker build -t bohrium_release -f package/docker/bohrium.dockerfile .

env:
  matrix:

      # Python v2
      - BH_STACK=openmp BH_OPENMP_PROF=true PYTHON_EXEC=python2.7
      - BH_STACK=opencl BH_OPENCL_PROF=true PYTHON_EXEC=python2.7

      # Python v3
      - BH_STACK=openmp BH_OPENMP_PROF=true PYTHON_EXEC=python3.5
      - BH_STACK=opencl BH_OPENCL_PROF=true PYTHON_EXEC=python3.5

notifications:
  slack: bohrium:BCAEW8qYK5fmkt8f5mW95GUe

script:
    - docker run -t -e BH_STACK -e BH_OPENMP_PROF -e BH_OPENCL_PROF -e PYTHON_EXEC bohrium_release
