services:
  - docker

language: c

compiler:
  - gcc

before_install:
  - docker pull bohrium/ubuntu:16.04
  - docker build -t bohrium_release -f package/docker/bohrium.dockerfile .

env:
  global:
    - BH_OPENMP_PROF=true
    - BH_OPENMP_VOLATILE=true
    - BH_OPENCL_PROF=true
    - BH_OPENCL_VOLATILE=true

  matrix:
    # All test_*.py scripts
    - BH_STACK=openmp PYTHON_EXEC=python2.7 TEST_EXEC="echo hej & ls && export"
      #- BH_STACK=openmp PYTHON_EXEC=python2.7 TEST_EXEC="python2.7 /bohrium/test/python/run.py /bohrium/test/python/tests/test_*.py && export & echo hej"
      #    - BH_STACK=openmp BH_OPENMP_MONOLITHIC=true PYTHON_EXEC=python2.7 TEST_EXEC="python2.7 /bohrium/test/python/run.py /bohrium/test/python/tests/test_*.py"
      #    - BH_STACK=opencl PYTHON_EXEC=python2.7 TEST_EXEC="python2.7 /bohrium/test/python/run.py /bohrium/test/python/tests/test_*.py"
      #    - BH_STACK=openmp PYTHON_EXEC=python3.5 TEST_EXEC="python3.5 /bohrium/test/python/run.py /bohrium/test/python/tests/test_*.py"
      #    - BH_STACK=opencl PYTHON_EXEC=python3.5 TEST_EXEC="python3.5 /bohrium/test/python/run.py /bohrium/test/python/tests/test_*.py"
      #
      #    # The test_benchmarks.py script
      #    - BH_STACK=openmp PYTHON_EXEC=python2.7 TEST_EXEC="python2.7 /bohrium/test/python/numpytest.py --file test_benchmarks.py"
      #    - BH_STACK=opencl PYTHON_EXEC=python2.7 TEST_EXEC="python2.7 /bohrium/test/python/numpytest.py --file test_benchmarks.py"
      #    - BH_STACK=openmp PYTHON_EXEC=python3.5 TEST_EXEC="python3.5 /bohrium/test/python/numpytest.py --file test_benchmarks.py"
      #    - BH_STACK=opencl PYTHON_EXEC=python3.5 TEST_EXEC="python3.5 /bohrium/test/python/numpytest.py --file test_benchmarks.py"
      #
notifications:
  slack: bohrium:BCAEW8qYK5fmkt8f5mW95GUe

script:
  - docker run -t -e BH_STACK -e BH_OPENMP_PROF -e BH_OPENCL_PROF -e BH_OPENMP_VOLATILE -e BH_OPENCL_VOLATILE -e BH_OPENMP_MONOLITHIC -e PYTHON_EXEC -e TEST_EXEC bohrium_release
