package:
  name: bohrium
  version: {{ GIT_DESCRIBE_TAG }}

build:
  number: {{ GIT_DESCRIBE_NUMBER }}

source:
  git_url: https://github.com/bh107/bohrium.git

requirements:
  build:
    - icu 54.*
    - bzip2
    - zlib
    - python
    - numpy >=1.8
    - cmake >=2.8
    - cython
    - swig
    - gcc
    - openblas
    - lapack

  run:
    - python
    - numpy >=1.8
    - gcc
    - openblas
    - lapack

about:
  home: http://bh107.org
  license: GPL3
  summery: "Bohrium Runtime System: Automatic Vector Parallelization in C, C++, CIL, and Python"

extra:
  maintainers:
   - Mads R. B. Kristensen <madsbk@gmail.com>
