package:
  name: bohrium
  version: {{ GIT_DESCRIBE_TAG }}

build:
  number: {{ GIT_DESCRIBE_NUMBER }}
  string: {{ GIT_BUILD_STR }}

source:
  git_url: https://github.com/bh107/bohrium.git

requirements:
  build:
    - python >=2.7
    - numpy >=1.8
    - cmake >=2.8
    - cheetah
    - cython
    - swig
    - boost-pic

  run:
    - python >=2.7
    - numpy >=1.8

about:
  home: http://bh107.org
  license: GPL3
  summery: "Bohrium Runtime System: Automatic Vector Parallelization in C, C++, CIL, and Python"

extra:
  maintainers:
   - Mads R. B. Kristensen <madsbk@gmail.com>
